import numpy as np

try:
    import chinook.build_lib as build_lib
    import chinook.experiment as experiment
    CHINOOK_AVAILABLE = True
except ImportError:
    CHINOOK_AVAILABLE = False

class ChinookWrapper:
    """
    The backend bridge to Chinook's ARPES matrix element calculator.
    Translates experimental beamline parameters into physical polarization vectors
    and evaluates the dipole transition rules.
    """
    def __init__(self):
        self.tb_model = None

    def build_model(self, tb_dict):
        """
        Initializes the tight-binding model directly from the dictionary
        generated by the DFT Suite.
        """
        if not CHINOOK_AVAILABLE:
            print("Chinook not installed. Running in Dummy Mode.")
            return
        
        self.tb_model = build_lib.gen_tb(tb_dict)

    def run_simulation(self, experiment_kwargs):
        """
        Translates UI beamline parameters into Chinook's experiment format,
        calculates matrix elements, and returns the intensity map.
        """
        # 1. Extract k-space bounds (kx, ky, E)
        kb = experiment_kwargs['k_bounds']
        num_x, num_y, num_e = kb['X'][2], kb['Y'][2], kb['E'][2]

        if not CHINOOK_AVAILABLE or self.tb_model is None:
            # Fallback for UI testing if Chinook isn't installed
            dummy_intensity = np.random.rand(num_x, num_y, num_e)
            return {'intensity_broadened': dummy_intensity}

        # 2. Extract Experimental Parameters
        hv = experiment_kwargs.get('photon_energy', 21.2)
        W = experiment_kwargs.get('work_function', 4.5)
        V0 = experiment_kwargs.get('inner_potential', 15.0)
        T = experiment_kwargs.get('temperature', 10.0)
        inc_angle = experiment_kwargs.get('incidence_angle', 55.0)
        pol_str = experiment_kwargs.get('polarization', "Linear Horizontal")
        me_mode = experiment_kwargs.get('matrix_element_mode', "Full Matrix Elements")

        # 3. Calculate Polarization Vector (A)
        # Assuming the sample normal is along Z, and the beam is in the XZ plane
        theta = np.radians(inc_angle)
        
        # p-pol (LH): Electric field is in the scattering plane, perpendicular to beam
        A_LH = np.array([np.cos(theta), 0.0, np.sin(theta)])
        # s-pol (LV): Electric field is perpendicular to the scattering plane (along Y)
        A_LV = np.array([0.0, 1.0, 0.0])
        
        if "Horizontal" in pol_str:
            A = A_LH
        elif "Vertical" in pol_str:
            A = A_LV
        elif "Right" in pol_str:
            A = (A_LH + 1j * A_LV) / np.sqrt(2)
        else: # Circular Left
            A = (A_LH - 1j * A_LV) / np.sqrt(2)

        # 4. Determine Matrix Element Toggles
        # If "Bare Spectral Function" is selected, we disable Matrix Elements
        ME_flag = "Off" not in me_mode

        # 5. Format the Domain (Cube) for Chinook
        domain = [
            kb['X'][0], kb['X'][1], num_x,
            kb['Y'][0], kb['Y'][1], num_y,
            kb['E'][0], kb['E'][1], num_e
        ]

        # 6. Build the Chinook ARPES Dictionary
        arpes_dict = {
            'cube': domain,
            'hv': hv,
            'W': W,
            'V0': V0,
            'T': T,
            'pol': A,
            'ME': ME_flag,
            'resolution': {'E': 0.02, 'k': 0.02} # Energy & Momentum broadening
        }

        # 7. Execute the ARPES Simulation
        try:
            exp = experiment.experiment(self.tb_model, arpes_dict)
            exp.run()
            
            # Chinook returns a flattened 1D array of intensities. 
            # We must reshape it to match our (kx, ky, E) grid.
            intensity_1d = np.real(exp.spectral)
            intensity_3d = intensity_1d.reshape((num_x, num_y, num_e))
            
        except Exception as e:
            raise RuntimeError(f"Chinook Calculation Error: {e}")

        return {'intensity_broadened': intensity_3d}